name: ci

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

env:
  NUXT_ENV_SITE_URL: "https://github.com/cal-overflow/portfolio" # This value does not matter here
  NUXT_ENV_FULL_NAME: Acceptance Tests
  NUXT_ENV_EMAIL_ADDRESS: cal-overflow@users.noreply.github.com

jobs:
  acceptance:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout ğŸ›
        uses: actions/checkout@master

      - name: Setup node env ğŸ—
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies ğŸ‘¨ğŸ»â€ğŸ’»
        run: npm ci --prefer-offline --no-audit

      - name: Run linter ğŸ‘€
        run: npm run lint

      - name: Run unit tests ğŸ§ª
        run: npm run unit

      # NOTE: being worked on in another branch
      # - name: Run e2e tests ğŸ¤–
      #   run: |
      #     mkdir e2e_specific_src_files
      #     git clone https://github.com/cal-overflow/example-portfolio-content.git e2e_specific_src_files
      #     cp -r e2e_specific_src_files/content/* src/content
      #     cp -r e2e_specific_src_files/assets/* src/assets

      #     echo "ls src/"
      #     ls src/
      #     echo "ls src/content/"
      #     ls src/content/
      #     echo "ls src/content/blog/"
      #     ls src/content/blog/

      #     export CYPRESS_RECORD_KEY=${{ secrets.CYPRESS_RECORD_KEY }}

      #     npm run e2e:headless:record
